[default]
src = "contracts"
out = "out"
libs = ["lib"]
tests = "test"
remappings = "remappings.txt"

[profile.default]
optimizer = true
optimizer_runs = 200
compiler_version = "0.8.18"
gas_reports = true
